import jsPDF from 'jspdf';

interface Order {
  id: string;
  customerName: string;
  SP: number;
  CP: number;
  profit: number;
  profitPercentage: number;
  status: string;
  createdAt: string;
}

export function generateInvoicePDF(order: Order, theme: 'dark' | 'light') {
  const pdf = new jsPDF();
  const isDark = theme === 'dark';
  
  // Set colors based on theme
  const primaryColor = isDark ? [255, 255, 255] : [0, 0, 0];
  const secondaryColor = isDark ? [156, 163, 175] : [107, 114, 128];
  const accentColor = [59, 130, 246]; // Blue
  
  // Background color
  if (isDark) {
    pdf.setFillColor(31, 41, 55); // gray-800
    pdf.rect(0, 0, 210, 297, 'F');
  }

  // Header
  pdf.setTextColor(...primaryColor);
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('SALES INVOICE', 20, 30);
  
  // Company info
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...accentColor);
  pdf.text('SalesFlow Systems', 20, 45);
  pdf.setTextColor(...secondaryColor);
  pdf.text('123 Business Street', 20, 52);
  pdf.text('Business City, BC 12345', 20, 59);
  pdf.text('Phone: (555) 123-4567', 20, 66);

  // Invoice details
  pdf.setTextColor(...primaryColor);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Invoice Details:', 120, 45);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...secondaryColor);
  pdf.text(`Invoice #: INV-${order.id}`, 120, 52);
  pdf.text(`Date: ${order.createdAt}`, 120, 59);
  pdf.text(`Status: ${order.status}`, 120, 66);

  // Customer info
  pdf.setTextColor(...primaryColor);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Bill To:', 20, 90);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...secondaryColor);
  pdf.text(order.customerName, 20, 97);

  // Line separator
  pdf.setDrawColor(...secondaryColor);
  pdf.line(20, 110, 190, 110);

  // Table header
  pdf.setTextColor(...primaryColor);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Description', 20, 125);
  pdf.text('Selling Price', 80, 125);
  pdf.text('Cost Price', 120, 125);
  pdf.text('Profit', 160, 125);

  // Table content
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...secondaryColor);
  pdf.text('Sales Order', 20, 140);
  pdf.text(`$${order.SP.toFixed(2)}`, 80, 140);
  pdf.text(`$${order.CP.toFixed(2)}`, 120, 140);
  pdf.text(`$${order.profit.toFixed(2)}`, 160, 140);

  // Line separator
  pdf.line(20, 150, 190, 150);

  // Totals
  pdf.setTextColor(...primaryColor);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Summary:', 20, 170);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...secondaryColor);
  pdf.text(`Total Amount: $${order.SP.toFixed(2)}`, 20, 180);
  pdf.text(`Profit Margin: ${order.profitPercentage.toFixed(2)}%`, 20, 190);

  // Footer
  pdf.setTextColor(...secondaryColor);
  pdf.setFontSize(10);
  pdf.text('Thank you for your business!', 20, 250);
  pdf.text('Generated by SalesFlow Systems', 20, 260);

  // Save PDF
  const filename = `invoice-${order.customerName.replace(/\s+/g, '-').toLowerCase()}-${order.id}.pdf`;
  pdf.save(filename);
}